enableTelemetry: false

nodeLinker: pnp

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: '@yarnpkg/plugin-typescript'

pnpEnableInlining: true

pnpMode: strict

yarnPath: .yarn/releases/yarn-3.2.4.cjs

packageExtensions:
    '@cypress-audit/pa11y@^1.3.1':
        dependencies:
            puppeteer: '*'
