name: E-Moto-X E2E tests
on:
    schedule:
        - cron: '0 1 * * *'
    push:
        # branches:
        #     - 'main'
    pull_request:
jobs:
    basic-ubuntu-20-v10:
        runs-on: ubuntu-20.04
        name: E2E on Chrome
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/cache@v2
              with:
                  path: |
                      '~/.cache/Cypress'
                      '.yarn/cache'
                  key: ${{ runner.os }}-cache-${{ hashFiles('**/yarn.lock') }}

            - name: Cypress info
              run: yarn cypress info & yarn cypress cache list --size

            - name: Yarn install
              run: yarn install --immutable

            - name: Cypress tests
              run: yarn cy:e2e --record --browser chrome
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORDING_KEY }}
                  # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # - name: Cypress install
            #   run: yarn dlx cypress

            # - name: Cypress tests
            #   uses: cypress-io/github-action@v4
            #   with:
            #       browser: chrome
            #       install-command: yarn install --immutable
            #       build: npm i -D cypress
            #       command-prefix: yarn dlx

            - name: Publish Test Report
              uses: mikepenz/action-junit-report@v3
              if: always() # always run even if the previous step fails
              with:
                  report_paths: 'build/cypress/test-results.xml'

            - name: Upload Lighthouse Report
              uses: actions/upload-artifact@v2
              if: always() # always run even if the previous step fails
              with:
                  name: lighthouse-report
                  path: build/cypress/lhreport.html

            - name: Upload failure screenshots
              uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots

            - name: Upload failure videos
              uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: cypress-videos
                  path: cypress/videos

    # basic-on-windows-v10:
    #   runs-on: windows-latest
    #   steps:
    #     - name: Checkout
    #       uses: actions/checkout@v2

    #     - name: Cypress tests
    #       uses: ./
    #       with:
    #         working-directory: examples/v10/basic
    #         build: npx cypress info

    # basic-on-mac-v10:
    #   runs-on: macos-latest
    #   steps:
    #     - name: Checkout
    #       uses: actions/checkout@v2

    #     - name: Cypress tests
    #       uses: ./
    #       with:
    #         working-directory: examples/v10/basic
    #         build: npx cypress info

    # skips the binary installation
    # shows that the job should not fail
    # https://github.com/cypress-io/github-action/issues/327
    # basic-without-binary-install-v10:
    #     runs-on: ubuntu-20.04
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v2

    #         - name: Cypress tests
    #           uses: cypress-io/github-action@v2
    #           with:
    #               working-directory: ./
    #               # since we do not install Cypress
    #               # we should not attempt to run tests
    #               runTests: false
    #           env:
    #               # skip the binary install
    #               CYPRESS_INSTALL_BINARY: 0
